name: test1

on:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.1.2
      
    steps:
      - uses: actions/checkout@v2
    
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          libcurl4-openssl-dev \
          libssl-dev
